### ISSUE TITLE
Historical Address Points

### ISSUE THREAD

**Issue by framoutar** [ccao-data/public#19]
### General description

Hello again -

I hope this message finds you well! I am requesting a version of the [Cook County Address Points](https://hub-cookcountyil.opendata.arcgis.com/datasets/5ec856ded93e4f85b3f6e1bc027a2472_0/about) dataset that includes every unique combination of postal address and PIN in Cook County from 2000-2015. The current Address Points dataset was published in 2016, but as a result it appears to be missing some older addresses that are no longer in use. 

Thank you for considering this request!

Fern

### Use case

I will use the dataset to connect the CCAO's public datasets to non-CCAO datasets that contain addresses and information from before 2015.

### Universe

- Every unique combination of postal address and PIN in Cook County from 2000-2015

### Unit of observation

- Individual postal address

### Restrictions and exclusions

n/a

### Data delivery format

Open Data asset

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by wrridgeway** [comment]
This data is available through what we already publish by combining two datasets:

[Assessor - Parcel Addresses](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Parcel-Addresses/3723-97qp/about_data)
[Assessor - Parcel Universe](https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Parcel-Universe/nj4t-kc8j/about_data)

You'd just join the parcel universe to the addresses by PIN and year in order to get lat long.
