### ISSUE TITLE
GitLab #23: Appraisal records

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/public#4]
### General description

I wanted to ask if you have pdf or other forms of document available that has records of real estate appraisal **scans**.

### Use case

I work at the Federal Reserve Bank of Chicago, and I am trying to develop a NLP (natural language processing) program to expedite document search processes. The requested pdf or image files will be used for the purpose of training the NLP model.

### Universe

Thousands of appraisal records (in images or pdf format) in Cook County if available.

### Unit of observation

Individual appraisal records

### Data delivery format

Other

### Citation and use of Assessor data

- [X] I agree to the above terms.

**Comment by jooseunglee** [comment]
Hi Dan, moving over here seeing your comment on Gitlab.

**Comment by wrridgeway** [comment]
I'll reach out to our valuations team to see what we can scrounge up.

**Comment by wrridgeway** [comment]
@jooseunglee After some investigation, the data department believes it's probably best to request this data through FOI at both the [Assessor's Office](https://cookcountyassessor.govqa.us/WEBAPP/_rs/(S(olqh5rpmlb0tmrmg3sciwggq))/SupportHome.aspx) and the [Board of Review](https://www.cookcountyboardofreview.com/what-we-do/freedom-information-act) rather than through the department's public data request repo. It's not data we maintain or have access to as a department, and the FOI department within the Assessor's Office is better suited to navigating the potential legal issues associated with the release of income and expense data that could be included in appraisals.
